### ISSUE TITLE
Add this please

### ISSUE THREAD

**Issue by addy005** [tgbot-collection/ytdlbot#5]
Please add quality (resolution) select buttons which appear after sending link
Second add heroku deploy button
Third if u can please add Google drive upload options

**Comment by BennyThink** [comment]
1. We choose best video and best audio at the first place. I would like to see a PR about this.
2. This is just a normal simple python program. Please refer to heroku python document if necessary. https://devcenter.heroku.com/articles/getting-started-with-python
3. this will require an oauth against your google account, which is too complicated from a bot's point of view.

In general, I think the first one is applicable - in order to bring convenience to users, we shall have a settings for preference resolution.
